version: "3.3"
services:
  flask:
    build:
      context: .
      dockerfile: flask-dockerfile
    ports:
      - "5000:5000"
  dash:
    build:
      context: .
      dockerfile: dash-dockerfile
    ports:
      - "8050:8050"